{% set name = "cubed-xarray" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b8e4428882a741bb37c3af4425963a60e2b082d2ebf0b8aa91717833a43ec303

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=42
    - setuptools_scm >=3.4
    - toml
  run:
    - python >=3.9
    - xarray >=2024.2.0
    - cubed >=0.6.3

test:
  imports:
    - cubed_xarray
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cubed-dev/cubed-xarray
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Interface for using cubed with xarray for parallel computation."
  doc_url: https://github.com/cubed-dev/cubed-xarray#readme
  dev_url: https://github.com/cubed-dev/cubed-xarray

extra:
  recipe-maintainers:
    - TomNicholas
    - tomwhite
