{% set name = "cubed-xarray" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b08a969656c9c05c7168f9eee78911b73d6ab31781c317984b490c8e9d984eac

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=42
    - setuptools_scm >=3.4
    - toml
  run:
    - python >=3.9
    - xarray >=2024.2.0
    - cubed >=0.6.3

test:
  imports:
    - cubed_xarray
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cubed-dev/cubed-xarray
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Interface for using cubed with xarray for parallel computation."
  doc_url: https://github.com/cubed-dev/cubed-xarray#readme
  dev_url: https://github.com/cubed-dev/cubed-xarray

extra:
  recipe-maintainers:
    - TomNicholas
    - tomwhite
