{% set name = "cubed-xarray" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ff1064199c248f78e1a79ca91f5effc8e6854ad47ba45d2d32a5d4f5c26f5482

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.11
    - setuptools >=42
    - setuptools_scm >=3.4
    - toml
  run:
    - python >=3.11
    - xarray >=2024.09.0
    - cubed >=0.24.0

test:
  imports:
    - cubed_xarray
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cubed-dev/cubed-xarray
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Interface for using cubed with xarray for parallel computation."
  doc_url: https://github.com/cubed-dev/cubed-xarray#readme
  dev_url: https://github.com/cubed-dev/cubed-xarray

extra:
  recipe-maintainers:
    - TomNicholas
    - tomwhite
